# Site settings
title: The Digital Backcountry
email: ryan@ryanstewart.net
description: "A blog about tools for the web, beer, the Creative Cloud, and other random bits."
baseurl: ""
url: "http://ryanstewart.net"

# Build settings
markdown: kramdown
permalink: pretty
